In [2]:
import numpy as np

In [3]:
d0q = np.asarray(
    [
        [7, 314],
        [1.5e6, 544],
        [50, 460],
        [1e3, 690],
        [2.5, 565],
        [5e14, 962],
        [40.5, 452],
        [4.2e2, 494],
        [3.11, 419],
        [0.43, 193],
        [22e-4, 267],
    ]
)

In [7]:
def arrh(T, d0, q):
    return 4.25e-7

In [8]:
arrh(1873, *d0q.T)

array([1.22565228e-08, 1.01203295e-09, 7.42400600e-12, 5.72140202e-17,
       4.37927454e-16, 7.43060483e-13, 1.00513583e-11, 7.02645974e-12,
       6.42426549e-12, 1.78298086e-06, 7.87794175e-11])

In [10]:
arrh(2073, *d0q.T)

array([8.57440159e-08, 2.94347606e-08, 1.28320766e-10, 4.11140641e-15,
       1.45067403e-14, 2.87968535e-10, 1.65332748e-10, 1.49925086e-10,
       8.61328976e-11, 5.89420441e-06, 4.11901034e-10])

In [9]:
arrh(2273, *d0q.T)

array([4.25958189e-07, 4.73099058e-07, 1.34324054e-09, 1.39243740e-13,
       2.59549438e-13, 3.90999404e-08, 1.66141869e-09, 1.86686055e-09,
       7.31350596e-10, 1.57878013e-05, 1.60973086e-09])

In [14]:
arrh(np.transpose([[1873, 2073, 2273]]), *d0q.T).T

array([[1.22565228e-08, 8.57440159e-08, 4.25958189e-07],
       [1.01203295e-09, 2.94347606e-08, 4.73099058e-07],
       [7.42400600e-12, 1.28320766e-10, 1.34324054e-09],
       [5.72140202e-17, 4.11140641e-15, 1.39243740e-13],
       [4.37927454e-16, 1.45067403e-14, 2.59549438e-13],
       [7.43060483e-13, 2.87968535e-10, 3.90999404e-08],
       [1.00513583e-11, 1.65332748e-10, 1.66141869e-09],
       [7.02645974e-12, 1.49925086e-10, 1.86686055e-09],
       [6.42426549e-12, 8.61328976e-11, 7.31350596e-10],
       [1.78298086e-06, 5.89420441e-06, 1.57878013e-05],
       [7.87794175e-11, 4.11901034e-10, 1.60973086e-09]])