In [1]:
from sympy import *
import numpy as np
from scipy.optimize import fsolve

In [2]:
gamma1 = Symbol(r"\gamma_1", positive=True)
gamma2 = Symbol(r"\gamma_2", positive=True)
gammab = Symbol(r"\gamma_b", positive=True)

psi1 = Symbol(r"\psi_1", positive=True)
psi2 = Symbol(r"\psi_2", positive=True)
psib = Symbol(r"\psi_b", positive=True)

In [3]:
eqns = [
    gamma1 / sin(psi1) - gamma2 / sin(psi2),    
    gamma1 / sin(psi1) - gammab / sin(psib),
    2 * pi - psi1 - psi2 - psib
]
eqns

[\gamma_1/sin(\psi_1) - \gamma_2/sin(\psi_2),
 \gamma_1/sin(\psi_1) - \gamma_b/sin(\psi_b),
 -\psi_1 - \psi_2 - \psi_b + 2*pi]

In [4]:
eqns_sub = [e.subs({
    gamma1: 1,
    gamma2: 2,
    gammab: 0.5
}) for e in eqns]
eqns_sub

[-2/sin(\psi_2) + 1/sin(\psi_1),
 -0.5/sin(\psi_b) + 1/sin(\psi_1),
 -\psi_1 - \psi_2 - \psi_b + 2*pi]

In [9]:
num_fun = lambdify([(psi1, psi2, psib)], eqns_sub)
num_fun(np.deg2rad([112, 72, 176]))

[np.float64(-1.024389705798951),
 np.float64(-6.089258770424232),
 np.float64(0.0)]

In [6]:
num_sol = fsolve(num_fun, np.deg2rad([112, , 180]))
np.rad2deg(num_sol)

array([-145.25208703,  324.49656274,  180.00000268])

In [7]:
np.cos(num_sol[2] / 2)

np.float64(-2.3406689192258866e-08)

In [10]:
terms = [
    gamma1 / sin(psi1),
    gamma2 / sin(psi2),    
    gammab / sin(psib),
    psi1 + psi2 + psib
]
terms

[\gamma_1/sin(\psi_1),
 \gamma_2/sin(\psi_2),
 \gamma_b/sin(\psi_b),
 \psi_1 + \psi_2 + \psi_b]

In [11]:
terms_sub = [t.subs({
    gamma1: 1,
    gamma2: 2,
    gammab: 0.5
}) for t in terms]
terms_sub

[1/sin(\psi_1), 2/sin(\psi_2), 0.5/sin(\psi_b), \psi_1 + \psi_2 + \psi_b]

In [13]:
terms_fun = lambdify([(psi1, psi2, psib)], terms_sub)
terms_fun(np.deg2rad([112, 72, 176]))

[np.float64(1.0785347426775833),
 np.float64(2.1029244484765344),
 np.float64(7.167793513101815),
 np.float64(6.283185307179586)]

In [16]:
def young(gamma, psi):
    return np.array(gamma) / np.sin(np.deg2rad(psi))

In [17]:
young([1, 2, 0.5], [112, 72, 176])

array([1.07853474, 2.10292445, 7.16779351])

In [22]:
from ipywidgets import interact

@interact(psi1=(0, 250), psi2=(0, 250))
def i_young(psi1=120, psi2=120):
    psis = [psi1, psi2, 360 - psi1 - psi2]
    return psis[2], young([1, 2, 0.5], psis)

interactive(children=(IntSlider(value=120, description='psi1', max=250), IntSlider(value=120, description='psi…

In [47]:
def f(x):
    y = young([1, 1.45, 0.5] ,[x[0], x[1], 360-x.sum()])
    return y[0] - y[1], y[1] - y[2]

s = fsolve(f, [120, 70])
s, 360 - s.sum(), f(s)

(array([158.86899991,  31.51536668]),
 np.float64(169.61563340962687),
 (np.float64(2.2808421817899216e-12), np.float64(-1.0405010186786967e-12)))

In [43]:
sin(pi - psi1)

sin(\psi_1)